[package]
name = "hw3-tuner"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tuner"
path = "tuner.rs"

[dependencies]
cpal = "0.13.0"
portaudio = "0.7.0"
hound = "3.4"
realfft = "3.0.0"
apodize = "1.0.0"
anyhow = "1.0.56"
num-complex = "0.4.1"